### PR TITLE
improve terminal colors, get rid of gap, refactored using yapf, fixed annotations

### PR DESCRIPTION
**Pull request by Montana**
Heyo, 

Just thought I'd add some color improvements, refactored it and made the annotations more consistent! Cool config!

### CODE REVIEW

**Comment by BrentonBeltrami** [comment]
> Heyo,
> 
> Just thought I'd add some color improvements, refactored it and made the annotations more consistent! Cool config!

Sweet, thank you for the help. I took inspiration from your tmux config a while back.

**Comment by Montana** [comment]
I heard this broke your terminal, yikes! Are you running `zsh`? 

Here's my `tmux.conf` in full:

```tmux

# improve colors
set -g default-terminal 'screen-256color'

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

set -g prefix2 C-s

# start window numbers at 1 to match keyboard order with tmux window order
set -g base-index 1
set-window-option -g pane-base-index 1

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# soften status bar color from harsh green to light gray
set -g status-style bg='#666666',fg='#aaaaaa'

# remove administrative debris (session name, hostname, time) in status bar
set -g status-left ''
set -g status-right ''

# increase scrollback lines
set -g history-limit 10000

# prefix -> back-one-character
bind-key C-b send-prefix
# prefix-2 -> forward-incremental-history-search
bind-key C-s send-prefix -2

# don't suspend-client
unbind-key C-z

# Local config
if-shell "[ -f ~/.tmux.conf.local ]" 'source ~/.tmux.conf.local'
```

**Comment by BrentonBeltrami** [comment]
I am running `zsh`. I have no idea why that tiny change broke it. I was just getting `[server exited]` on launch.

**Comment by Montana** [comment]
Do this please:

```bash
pkill tmux
strace -tt -fostrace.out tmux new
```
Then show me any `strace.out*` files.

**Comment by BrentonBeltrami** [comment]
> Do this please:
> 
> ```shell
> pkill tmux
> strace -tt -fostrace.out tmux new
> ```
> 
> Then show me any `strace.out*` files.

I ran this but I cannot find `stract.out*` files being created.

**Comment by Montana** [comment]
Oh okay I'm on Linux, try if you're on macOS: 

```bash
sudo dtruss -a tmux
```

**Comment by BrentonBeltrami** [comment]
``` 
dtrace: system integrity protection is on, some features will not be available

	PID/THRD  RELATIVE  ELAPSD    CPU SYSCALL(args) 		= return
missing or unsuitable terminal: xterm-kitty

CALL                                        COUNT
```

This is the result.

**Comment by Montana** [comment]
One last thing, client and server logs could be accessed this way:

```bash
cat tmux-client-*.log
```

```bash
cat tmux-server-*.log
```

**Comment by BrentonBeltrami** [comment]
When running `cat tmux-server-*.log` I get `zsh: no matches found: tmux-server-*.log` whether or not I am running `tmux`.

**Comment by Montana** [comment]
I think I know the issue here, 

For clarity, `kitty` seems to use its own `terminfo` file called `xterm-kitty`, and `Alacritty` and `iterm2` both use the good-old `xterm-256color`.

So, `tmux` does not support multiple `terminfo`. You will need to kill all existing tmux sessions and start a new one. So run:

```bash
tmux list-sessions
```
See if any sessions pop up, if they do, you need to run: 

```bash
tmux kill-server
```

**Comment by BrentonBeltrami** [comment]
I've killed the tmux server a bunch. I have no sessions running now. 

When I add `export TERM=screen-256color` to my `.zshrc` instead of `export TERM=xterm-256color` my tmux status bar turns grey. Is that the goal?

**Comment by Montana** [comment]
That would now mean you're on `256`, but more importantly your `syntax` will be a lot more colorful. If you want I can share my personal `.vimrc` with you? Then maybe this will make more sense. I haven't looked at your `.vimrc`, but I'm assuming you're using the `call plug#begin()` for vim plugins?

**Comment by BrentonBeltrami** [comment]
Yes I am using `call plug#begin()`. I would love to see your .vimrc. Also what plugins do you suggest?

**Comment by Montana** [comment]
I will send you a collaboration invite on my `.vimrc`, you'll see all the plugins I use!

**Comment by Montana** [comment]
Invited to be a collaborator!

**Comment by BrentonBeltrami** [comment]
One more thing, I basically only use tmux in the terminal so I had it launch by default with `[[ $TERM != "screen" ]] && exec tmux` but that seems to break with the improved colors & requires me to manually launch tmux. Do you know a way around this?

**Comment by Montana** [comment]
A couple of things here, If you want to have a single `tmux` session, put the following in your `~/.zshrc` for zsh:

```bash
tmux attach &> /dev/null

if [[ ! $TERM =~ screen ]]; then
    exec tmux
fi
```

The `tmux attach` line is to make sure if there is a session it attaches to and if there was no session you will not get the warning about "no session".

Secondly, you might want to get rid of the `export TERM=screen-256color` in `.zshrc` and added the `-2` argument to `tmux`, so for example: 

```bash
[[ $- != *i* ]] && return
[[ $TERM != screen* ]] && exec tmux -2
```

Hope this helps bud.

**Comment by BrentonBeltrami** [comment]
Thank you, both of those seem to work. Is the `-2` argument for colors? I am not getting anything when I google it.

**Comment by Montana** [comment]
So for example in my system, it was not working and I had this similar issue, so I have to tell `tmux` my terminal supports `256 colors` by using the '-2' argument. You can add this line to your `~/.zshrc` to always call tmux with '-2':

```bash
alias tmux="tmux -2"
```

**Comment by BrentonBeltrami** [comment]
No worries, thank you very much for walking me through this. I have learned a bunch. Also thanks for sharing the `.vimrc`!

**Comment by Montana** [comment]
Hey no worries @BrentonBeltrami, 

I apologize for making your `tmux` go completely "insane", but I guess I was able to redeem myself to a degree. Of course man, feel free to use it my man, that's a really good setup, I recommend it highly, it's for my job, and I use it everyday. You can of course play off it and add to it, remove off it, and have a great foundation. 

If anything else comes up, please just hit me up at montana@linux.com. 

Thanks Brenton. 

Cheers,
Montana Mendy

**Pull request merged**
